name: Deploy all user-domain microservices to EC2

on:
  push:
    branches:
      - QA
    paths:
      - 'Backend/Domain/User/**'
      - '.github/workflows/deploy-user-domain.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          docker pull cristian2000p/users-service
          docker pull cristian2000p/profile-service
          docker pull cristian2000p/notification-service
          docker pull cristian2000p/user-settings-service
          docker pull cristian2000p/user-status-service
          docker pull cristian2000p/user-notes-service

          docker stop users-service || true && docker rm users-service || true
          docker run -d --name users-service -p 3001:3001 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_users \
            cristian2000p/users-service

          docker stop profile-service || true && docker rm profile-service || true
          docker run -d --name profile-service -p 3006:3006 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_profiles \
            cristian2000p/profile-service

          docker stop notification-service || true && docker rm notification-service || true
          docker run -d --name notification-service -p 3003:3003 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_notifications \
            cristian2000p/notification-service

          docker stop user-settings-service || true && docker rm user-settings-service || true
          docker run -d --name user-settings-service -p 3007:3007 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_user_settings \
            cristian2000p/user-settings-service

          docker stop user-status-service || true && docker rm user-status-service || true
          docker run -d --name user-status-service -p 3008:3008 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_user_status \
            cristian2000p/user-status-service

          docker stop user-notes-service || true && docker rm user-notes-service || true
          docker run -d --name user-notes-service -p 3009:3009 \
            -e MONGO_URI=mongodb://172.17.0.1:27017/notary_user_notes \
            cristian2000p/user-notes-service
