name: Deploy User Settings Service

on:
  push:
    branches: [ QA ]
    paths:
      - 'backend/user-domain/user-settings-service/**'
  workflow_dispatch:   # <— añade esta línea

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t cristian2000p/user-settings-service ./backend/user-domain/user-settings-service
          docker push cristian2000p/user-settings-service

      - name: Deploy to EC2 instance 3
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.EC2_HOST_3 }}
          username: ${{ secrets.EC2_USER_3 }}
          key:      ${{ secrets.EC2_KEY_3 }}
          script: |
            # opcional: crear un .env en remoto
            cat > ~/user-settings-service/.env <<EOF
            PORT=3001
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

            cd ~/user-settings-service

            # elimina versión anterior
            sudo docker rm -f user-settings-service || true

            # tira la última imagen
            sudo docker pull cristian2000p/user-settings-service:latest

            # arranca con --env-file
            sudo docker run -d \
              --name user-settings-service \
              --restart always \
              --env-file .env \
              -p 3001:3001 \
              cristian2000p/user-settings-service:latest
