name: Deploy user-status-service to EC2 (second instance)

on:
  push:
    branches:
      - QA
    paths:
      - 'backend/user-domain/user-status-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-status-service ./backend/user-domain/user-status-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-status-service

    - name: SSH and deploy on second EC2 instance
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_2 }}
        username: ${{ secrets.EC2_USER_2 }}
        key: ${{ secrets.EC2_KEY_2 }}
        script: |
          docker rm -f user-status-service || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user-status-service
          docker run -d -p 3008:3008 --name user-status-service ${{ secrets.DOCKERHUB_USERNAME }}/user-status-service
