name: deploy

on:
  push:
    branches:
      - QA

env:
  EC2_USER: ec2-user
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_KEY: ${{ secrets.EC2_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub and Push All Images
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          docker build -t jeffri1997/users-service ./Backend/Domain/User/GetUser
          docker push jeffri1997/users-service

          docker build -t jeffri1997/profile-service ./Backend/Domain/User/Profile
          docker push jeffri1997/profile-service

          docker build -t jeffri1997/notification-service ./Backend/Domain/User/Notification
          docker push jeffri1997/notification-service

          docker build -t jeffri1997/user-settings-service ./Backend/Domain/User/UserSettings
          docker push jeffri1997/user-settings-service

          docker build -t jeffri1997/user-status-service ./Backend/Domain/User/UserStatus
          docker push jeffri1997/user-status-service

          docker build -t jeffri1997/user-notes-service ./Backend/Domain/User/UserNotes
          docker push jeffri1997/user-notes-service

      - name: Deploy all user-domain microservices to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            docker pull jeffri1997/users-service
            docker pull jeffri1997/profile-service
            docker pull jeffri1997/notification-service
            docker pull jeffri1997/user-settings-service
            docker pull jeffri1997/user-status-service
            docker pull jeffri1997/user-notes-service

            docker stop users-service || true && docker rm users-service || true
            docker run -d --name users-service -p 3001:3001 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/notary_users \
              jeffri1997/users-service

            docker stop profile-service || true && docker rm profile-service || true
            docker run -d --name profile-service -p 3006:3006 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/notary_profiles \
              jeffri1997/profile-service

            docker stop notification-service || true && docker rm notification-service || true
            docker run -d --name notification-service -p 3003:3003 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/notificationsdb \
              jeffri1997/notification-service

            docker stop user-settings-service || true && docker rm user-settings-service || true
            docker run -d --name user-settings-service -p 3007:3007 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/usersettingsdb \
              jeffri1997/user-settings-service

            docker stop user-status-service || true && docker rm user-status-service || true
            docker run -d --name user-status-service -p 3008:3008 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/user-status-db \
              jeffri1997/user-status-service

            docker stop user-notes-service || true && docker rm user-notes-service || true
            docker run -d --name user-notes-service -p 3009:3009 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/notarydb \
              jeffri1997/user-notes-service
