name: Deploy Users Service

on:
  push:
    branches:
      - QA
    paths:
      - 'backend/user-domain/users-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t cristian2000p/users-service ./backend/user-domain/users-service
          docker push cristian2000p/users-service

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f users-service || true
            docker pull cristian2000p/users-service
            docker run -d --name users-service -p 3001:3001 \
              -e MONGO_URI=mongodb://172.17.0.1:27017/notifications_users \
              -e PORT=3001 \
              -e JWT_SECRET=miclaveultrasecreta123 \
              cristian2000p/users-service
